// INSTANCIA DE JARVIS
let Jarvis = new Artyom(), respuestaMode = 'quick', timeouts = [], freeSayFlag = false, canPlayVideo = {};

const commands = {
  saludos: ['Hola', 'hola', 'Holi', 'Buenos dias', 'Buenas tardes', 'Buenas noches', 'Buenas', 'Hello', 'Hi', 'Good Morning', 'Good afternoon', 'Good night'],
  modoReposo: ['reposo'],
  modoFrasesLentas: ['lento', 'cortas', 'lento'], // En pruebas(versión beta)
  modoFrasesNormales: ['normal', 'normales', 'normal'], // En pruebas(versión beta)
  modoFrasesLargas: ['largo', 'largas', 'rapido'],
  silenciar: ['silencio', 'callate'], // En pruebas(versión beta)
  galeriasysecciones: ['galerias', 'galerias y secciones', 'Galerías', 'Galerías y secciones', 'Secciones'], //7
  siMeGustariaOirMas: ['si me gustaría', 'si gracias', 'Me gustaría'],
  noMeGustariaOirMas: ['En otro momento', 'Mejor luego', 'Por ahora no', 'No, de momento'],
  espaciosyarquitectura: ['Espacios', 'Espacios y arquitectura', 'Arquitectura'], // 11
  historia: ['Historia de Arco', 'Arco', 'Historia'],
  novedadesDosMilVeintiDos: ['Novedades 2022', 'Novedades', '2022'],
  puntuacion: ['Uno', 'dos', 'Tres', 'Cuatro', 'Cinco']
}

// reposoTrack
let videoDinamicLocalSrcArr = [
  { src: "/media/Videos/VIDEOSCHICAARCO2022/11.IDLE/IDLE.mp4", id: "reposoTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/1.SALUDOSYLISTADO/SALUDOCHICA1.mp4", id: "saludoTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/1.SALUDOSYLISTADO/SALUDOCHICA2.mp4", id: "saludoSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/40MASUNO/40MASUNOGALERIA1.mp4", id: "galeriasMasunoFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/40MASUNO/40MASUNOGALERIA2.mp4", id: "galeriasMasunoSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/NUNCALOMISMO/NUNCALOMISMO1.mp4", id: "galeriasNuncaFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/NUNCALOMISMO/NUNCALOMISMO2.mp4", id: "galeriasNuncaSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/OPENING/OPENING1.mp4", id: "galeriasOpeningFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/OPENING/OPENING2.mp4", id: "galeriasOpeningSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/PROYECTOSARTISTAS/PROYECTOSARTISTAS.mp4", id: "galeriasProgramaFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/PROGRAMAGENERAL/PROGRAMAGENERAL1.mp4", id: "galeriasProgramaSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/2.GALERIASYSECCIONES/PROGRAMAGENERAL/PROGRAMAGENERAL2.mp4", id: "galeriasArtistasTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/FUNDACIONARCO/FUNDACION1.mp4", id: "architectureFundacionFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/FUNDACIONARCO/FUNDACION2.mp4", id: "architectureFundacionSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/OTROSESPACIOS/ESPACIOS1.mp4", id: "architectureEspaciosFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/OTROSESPACIOS/ESPACIOS2Y3.mp4", id: "architectureEspaciosSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/PROGRAMAGENERAL/PROGRAMAGENERALARQ.mp4", id: "architectureProgramaTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/SALA40MASUNO/SALA40MASUNO.mp4", id: "architectureSalaTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/SALAVIP/SALAVIP.mp4", id: "architectureVipTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/TERRAZAARCO/TERRAZAARCO.mp4", id: "architectureArcoTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/4.HISTORIADEARCO/HISTORIADEARCO1.mp4", id: "historyArcoFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/4.HISTORIADEARCO/HISTORIADEARCO2.mp4", id: "historyArcoThirdTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/5.NOVEDADES2022/NOVEDADES1.mp4", id: "newsFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/5.NOVEDADES2022/NOVEDADES2.mp4", id: "newsSecTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/5.NOVEDADES2022/NOVEDADES1.mp4", id: "newsThirdTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/6.PREGUNTAPARADECISIONUSUARIO/PREGUNTADECISION.mp4", id: "anotherThemeTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/7.LISTADODESPUESDERESPUESTASI/LISTADODESPUESDERESPUESTASI.mp4", id: "listYesChicaTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/8.PREGUNTAENCUESTA/PREGUNTAENCUESTASOBREARCO.mp4", id: "openQuestionTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/9.PREGUNTAENCUESTAAVATAR/PREGUNTAENCUESTASOBREAVATAR.mp4", id: "scoreTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/10.DESPEDIDAS/DESPEDIDA1.mp4", id: "byeFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/10.DESPEDIDAS/DESPEDIDA2.mp4", id: "byeSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/11.IDLE/IDLE.mp4", id: "reposoChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/1.SALUDOSYLISTADO/SALUDO1.mp4", id: "saludoChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/1.SALUDOSYLISTADO/SALUDO2.mp4", id: "saludoChicoSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/40MASUNO/40MASUNOGALERIA1.mp4", id: "galeriasChicoMasunoFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/40MASUNO/40MASUNOGALERIA2.mp4", id: "galeriasChicoMasunoSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/NUNCALOMISMO/NUNCALOMISMO1.mp4", id: "galeriasChicoNuncaFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/NUNCALOMISMO/NUNCALOMISMO2.mp4", id: "galeriasChicoNuncaSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/OPENING/OPENING1.mp4", id: "galeriasChicoOpeningFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/OPENING/OPENING2.mp4", id: "galeriasChicoOpeningSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/PROGRAMAGENERAL/PROGRAMAGENERALGALERIAS1.mp4", id: "galeriasChicoProgramaFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/PROGRAMAGENERAL/PROGRAMAGENERALGALERIAS2.mp4", id: "galeriasChicoProgramaSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/2.GALERIASYSECCIONES/PROYECTOSARTISTAS/PROYECTOARTISTAS.mp4", id: "galeriasChicoArtistasTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/FUNDACIONARCO/FUNDACION1.mp4", id: "architectureChicoFundacionFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/FUNDACIONARCO/FUNDACION2.mp4", id: "architectureChicoFundacionSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/OTROSESPACIOS/ESPACIOS1.mp4", id: "architectureChicoEspaciosFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICAARCO2022/3.ESPACIOSYARQUITECTURA/OTROSESPACIOS/ESPACIOS2Y3.mp4", id: "architectureChicoEspaciosSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/PROGRAMAGENERAL/PROGRAMAGENERALARQUI.mp4", id: "architectureChicoProgramaTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/SALA40MASUNO/SALA40MASUNO.mp4", id: "architectureChicoSalaTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/SALAVIP/SALAVIP.mp4", id: "architectureChicoVipTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/3.ESPACIOSYARQUITECTURA/TERRAZAARCO/TERRAZAARCO.mp4", id: "architectureChicoArcoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/4.HISTORIADEARCO/HISTORIA1.mp4", id: "historyChicoArcoFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/4.HISTORIADEARCO/HISTORIA2.mp4", id: "historyChicoArcoThirdTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/5.NOVEDADES2022/NOVEDADES1.mp4", id: "newsChicoFirstTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/5.NOVEDADES2022/NOVEDADES2.mp4", id: "newsChicoSecTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/5.NOVEDADES2022/NOVEDADES3.mp4", id: "newsChicoThirdTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/6.PREGUNTAPARADECISIONUSUARIO/PREGUNTADECISION.mp4", id: "anotherThemeChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/7.LISTADODESPUESDERESPUESTASI/LISTADODESPUESDERESPUESTASI.mp4", id: "listYesChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/8.PREGUNTAENCUESTA/PREGUNTASOBREARCO.mp4", id: "openQuestionChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/9.PREGUNTAENCUESTAAVATAR/PREGUNTASOBREAVATAR.mp4", id: "scoreChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/10.DESPEDIDAS/DESPEDIDA1.mp4", id: "byeFirstChicoTrack" },
  { src: "/media/Videos/VIDEOSCHICOARCO2022/10.DESPEDIDAS/DESPEDIDA2.mp4", id: "byeSecChicoTrack" },
]